title: Fusion Guides
description: Tutorials, Guides & Fixes

remote_theme: jekyll/minima

plugins:
  - jekyll-feed

markdown: kramdown

show_excerpts: true

header_pages:
  - index.md
  - guides.md
  - tutorials.md
  - fixes.md

minima:
  skin: dark
