title: Fusion Guides
description: Tutorials, Guides & Fixes

theme: minima

markdown: kramdown

plugins:
  - jekyll-feed

show_excerpts: true

header_pages:
  - index.md
  - guides.md
  - tutorials.md
  - fixes.md

minima:
  skin: dark
  minima:
  skin: dark
